---
name: "Sets up language needs"
description: "Based on the provided inputs, sets up the language environment dependencies"
inputs:
  ruby:
    description: "Set up Ruby environment"
    default: "false"
  ruby-version:
    description: "Ruby version to use"
    default: "default"
  node:
    description: "Set up Node environment"
    default: "false"
  node-version:
    description: "Node version to use"
    default: "18"
  deno:
    description: "Set up Deno environment"
    default: "false"
  deno-version:
    description: "Deno version to use"
    default: "v1.x"

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      if: ${{ inputs.ruby == 'true' }}
      with:
        bundler-cache: true
        ruby-version: ${{ inputs.ruby-version }}
        rubygems: latest
      env:
        RAILS_ENV: test
        BUNDLE_WITH: "ci"

    - name: Install Node
      uses: actions/setup-node@v4
      if: ${{ inputs.node == 'true' }}
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: "npm"

    - name: Install npm dependencies
      if: ${{ inputs.node == 'true' }}
      shell: bash
      run: |
        npm ci

    - uses: denoland/setup-deno@v1
      if: ${{ inputs.deno == 'true' }}
      with:
        deno-version: ${{ inputs.deno-version }}
