name: "Run Sorbet Update"
description: "Validates that all the Sorbet types are up to date."

runs:
  using: "composite"
  steps:
    - uses: yettoapp/actions/setup-languages@main
      with:
        ruby: true

    - if: ${{ env.DATABASE_URL }}
      name: Install pg_dump and package dependencies
      shell: bash
      run: |
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
        sudo apt update
        sudo apt-get install -q -y \
          postgresql-client

    - if: ${{ env.DATABASE_URL }}
      name: Set up the Rails database for Tapioca DSL reflection/generation
      env:
        RAILS_ENV: development
      shell: bash
      run: |
        bin/rails db:test:prepare

    - name: Update RBI files
      id: update
      shell: bash
      run: $GITHUB_ACTION_PATH/../script/sorbet --update

    - name: Commit types
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[auto-rbi]: Update RBI files"

        commit_user_name: Sisyphus
        commit_user_email: sisyphus@yetto.app
        commit_author: Sisyphus <sisyphus@yetto.app>
