---
name: "Sets up whatever Fly needs"
description: "Based on the provided inputs, sets up the Fly CLIs"
inputs:
  flyctl-version:
    description: "Set Fly version"
    default: 0.1.84

runs:
  using: "composite"
  steps:
    - uses: superfly/flyctl-actions/setup-flyctl@master
      with:
        version: ${{ inputs.flyctl-version }}
