#!/usr/bin/env bash

set -e

function usage() {
  echo "Usage:"
  echo "$0 [options]"
  echo ""
  echo "  Options:"
  echo "    -u/--update           Update license information"
  echo "    -v/--verify           Verify license information"
  echo "    -g/--generate         Generate CSV license data"
  echo "    -h/--help             Display this help message"
  echo ""
  exit 1
}

while [ "$1" != "" ]; do
    case $1 in
    -v | --verify)
        echo "Verifying dependency licenses ..."
        bin/bundle exec licensed env -c .licensed.yml
        bin/bundle exec licensed list -c .licensed.yml
        bin/bundle exec licensed status -c .licensed.yml
        
        EXIT_CODE=$?
        if [ $EXIT_CODE -ne 0 ]; then
          echo
          echo "*** When fixed, please run 'script/licenses -c' to update the license cache. ***"
          echo
        fi

        exit $EXIT_CODE
        ;;
    -u | --update)
        echo "Caching dependency licenses ..."
        bin/bundle exec licensed cache -c .licensed.yml
        ;;
    -g | --generate)
        echo "Generating CSV licenses ..."
        bin/bundle exec rake licenses:generate
        ;;
    -h | --help)
        usage
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done
