#!/usr/bin/env bash

set -e

function usage() {
  echo "Usage:"
  echo "$0 [options]"
  echo ""
  echo "  Options:"
  echo "    -u/--update           Update tapioca RBI files"
  echo "    -v/--verify           Verify tapioca RBI files"
  echo "    -h/--help             Display this help message"
  echo ""
  exit 1
}


while [ "$1" != "" ]; do
    case $1 in
    -u | --update)
        if [ -n "${DATABASE_URL+1}" ]; then
            bin/rails db:migrate
        fi

        echo "Regenerating Tapioca RBI files ..."
        bundle exec tapioca gem
        echo "Generating Tapioca annotations ..."
        bundle exec tapioca annotations
        echo "Updating Tapioca DSL files ..."
        bundle exec tapioca dsl
        ;;
    -v | --verify)
        echo "Verify Sorbet types..."
        bin/bundle exec srb tc
        echo "Verify gem RBIs are up-to-date ..."
        bin/tapioca gem --verify
        echo "Verify duplicates in shims ..."
        bin/tapioca check-shims
        ;;
    -h | --help)
        usage
        ;;
    *)
        usage
        exit 1
        ;;
    esac
    shift
done
