---
name: "Run the test suite"
description: "Runs the test suite for Ruby apps."
inputs:
  github_token:
    description: "The token used when calling GitHub API"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      run: |
        script/ci
      env:
        COVERAGE: "1"

    - name: Install helpers
      shell: bash
      run: |
        echo "$GITHUB_ACTION_PATH/bin" >> $GITHUB_PATH

    - name: Post coverage report
      shell: bash
      id: coverage_report
      env:
        NO_COLOR: "1"
      run: |
        coverage_report="$(bundle exec ruby $GITHUB_ACTION_PATH/helpers/report.rb || true)"

        echo "report<<EOF"$'\n'"$coverage_report"$'\n'EOF >> $GITHUB_OUTPUT

    # - uses: mshick/add-pr-comment@v2
    #   if: "${{ steps.coverage_report.outputs.report != '' }}"
    #   with:
    #     message: |
    #       <!-- type: code_coverage -->
    #       ## Code coverage

    #       ```
    #        ${{ steps.coverage_report.outputs.report }}
    #       ```
    #     repo-token: ${{ inputs.github_token }}
