---
name: "Construct the final Dockerfile"
description: "Allows one to use template variables from within a Dockerfile"
inputs:
  template:
    description: "The name of the template to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Fetch template
      shell: bash
      run: |
        gh api repos/yettoapp/images/contents/${{ inputs.template }} --jq '.content' | base64 --decode > Dockerfile.template

    - name: Construct Dockerfile
      shell: bash
      id: coverage_report
      env:
        NO_COLOR: "1"
      run: |
        bundle exec ruby $GITHUB_ACTION_PATH/helpers/construct.rb || true
