name: Runs a Ruby test suite

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
    inputs:
      setup_postgresql_and_redis:
        required: false
        type: boolean
        default: false
      postgres_username:
        required: false
        type: string
        default: ""
      postgres_database_name:
        required: false
        type: string
        default: ""
      node:
        required: false
        type: boolean
        default: false
      system_tests:
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

jobs:
  test_setup:
    runs-on:
      labels: ubuntu-latest-m
    outputs:
      setup_postgresql_and_redis: ${{ steps.check_services.outputs.setup_postgresql_and_redis }}

    steps:
      - id: check_services
        run: |
          echo "setup_postgresql_and_redis=${{ inputs.setup_postgresql_and_redis }}" >> $GITHUB_OUTPUT

  test_with_postgres_and_redis:
    runs-on:
      labels: ubuntu-latest-m
    needs: test_setup
    if: ${{ inputs.setup_postgresql_and_redis == true }}
    timeout-minutes: 10

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${{ inputs.postgres_username }}
      RAILS_ENV: test
      REDIS_URL: redis://localhost:6379/0
      DATABASE_URL: "postgresql://${{ inputs.postgres_username }}:postgres@localhost:5432/${{ inputs.postgres_database_name }}"
      RAILS_MASTER_KEY: supersecret
      SLACK_LOG_URL: https://slack.com/the_log_room

    # Service containers to run; note that this is duplicated
    # in sorbet.yml due to a limitation in GitHub Actions
    # (services can only be defined per job)
    services:
      postgres:
        # Docker Hub image name
        image: postgres:16-bookworm # POSTGRES_VERSION
        # The postgres container requires the postgres user to be setup with a password in order to start it due to security
        # reasons. It also can't read from the env var above for some reason
        env:
          PGUSER: "${{ env.POSTGRES_USER }}"
          POSTGRES_USER: "${{ env.POSTGRES_USER }}"
          POSTGRES_PASSWORD: "${{ env.POSTGRES_PASSWORD }}"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd 'pg_isready' --health-interval 10s --health-timeout 5s --health-retries 5
        # Maps tcp port 5432 on service container to the host
        ports: ["5432:5432"]
      redis:
        # Docker Hub image name
        image: redis:7-bookworm
        ports: ["6379:6379"]
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping" --health-interval 10s --health-timeout
          5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.gh_token }}

      - uses: yettoapp/actions/run-ruby-tests@main
        with:
          github_token: ${{ secrets.gh_token }}
          node: ${{ inputs.node }}
          system_tests: ${{ inputs.system_tests }}

  test_without_services:
    runs-on:
      labels: ubuntu-latest-m
    needs: test_setup
    if: ${{ inputs.setup_postgresql_and_redis == false }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.gh_token }}

      - uses: yettoapp/actions/run-ruby-tests@main
        with:
          github_token: ${{ secrets.gh_token }}
          node: ${{ inputs.node }}
          system_tests: ${{ inputs.system_tests }}
