name: Test Docker build

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      fly_token:
        required: true
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
    inputs:
      app_name:
        description: "Name of the app to deploy"
        required: true
        type: string
      fly_args:
        required: false
        default: ""
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  test-build:
    runs-on: ubuntu-latest-m
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.gh_token }}

      - uses: yettoapp/actions/setup-fly@main

      - name: Build production Dockerfile
        timeout-minutes: 10
        run: |
          flyctl deploy --remote-only --build-only \
          -a ${{ inputs.app_name }} \
          --build-arg REGISTRY=ghcr.io/ \
          --build-secret AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --build-secret AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --build-secret HONEYCOMB_API_KEY=${{ secrets.HONEYCOMB_API_KEY }} \
          --build-secret FLY_METRICS_TOKEN=${{ secrets.FLY_METRICS_TOKEN }} \
          ${{ inputs.fly_args }} \
          -c vendor/fly/fly-production.toml \

        env:
          FLY_API_TOKEN: ${{ secrets.fly_token }}
